# Generated by Django 5.1.7 on 2025-03-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('banco', models.CharField(choices=[('pan', 'PAN'), ('facta', 'Facta'), ('safra', 'Safra')], max_length=10)),
                ('servico', models.CharField(choices=[('inss', 'INSS'), ('fgts', 'FGTS')], max_length=10)),
            ],
        ),
    ]
